"""Add user_id to bookings

Revision ID: f78dd4a42122
Revises: fad5e629115b
Create Date: 2025-12-25 17:17:04.236073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78dd4a42122'
down_revision: Union[str, Sequence[str], None] = 'fad5e629115b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'user_id')
    # ### end Alembic commands ###
