"""Add room_number to bookings

Revision ID: fad5e629115b
Revises: 867ac8677506
Create Date: 2025-12-25 16:58:34.416477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fad5e629115b'
down_revision: Union[str, Sequence[str], None] = '867ac8677506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'room_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('bookings_room_number_fkey'), 'bookings', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('bookings_room_number_fkey'), 'bookings', 'rooms', ['room_number'], ['room_number'])
    op.alter_column('bookings', 'room_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
